apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nslookup redis; do echo waiting for redis; sleep 2; done']
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 192.168.64.12:5000/worker:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: REDIS_HOST
              value: redis